name = "dentalign"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Static assets
assets = { directory = ".open-next/assets", binding = "ASSETS" }
